# Generated by Django 5.0.2 on 2024-02-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5000)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50000)),
                ('content', models.CharField(max_length=500000)),
            ],
            options={
                'db_table': 'carrers',
                'ordering': ['created_datetime'],
            },
        ),
    ]
